apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../kserve-built
  - ./user_cluster_roles.yaml

namespace: opendatahub

patches:
  - path: kserve-controller-manager-patch.yaml
  - path: inferenceservice-config-patch.yaml

configMapGenerator:
- envs:
  - params.env
  name: kserve-parameters

generatorOptions:
  disableNameSuffixHash: true

vars:
- fieldref:
    fieldpath: data.kserve-controller
  name: kserve-controller
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: kserve-parameters
- fieldref:
    fieldpath: data.kserve-alibi-explainer
  name: kserve-alibi-explainer
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: kserve-parameters
- fieldref:
    fieldpath: data.kserve-alibi-explainer-version
  name: kserve-alibi-explainer-version
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: kserve-parameters
- fieldref:
    fieldpath: data.kserve-art-explainer
  name: kserve-art-explainer
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: kserve-parameters
- fieldref:
    fieldpath: data.kserve-art-explainer-version
  name: kserve-art-explainer-version
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: kserve-parameters
- fieldref:
    fieldpath: data.kserve-storage-initializer
  name: kserve-storage-initializer
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: kserve-parameters
- fieldref:
    fieldpath: data.kserve-agent
  name: kserve-agent
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: kserve-parameters
- fieldref:
    fieldpath: data.kserve-router
  name: kserve-router
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: kserve-parameters

configurations:
  - params.yaml
