apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
- envs:
  - params.env
  name: codeflare-stack-config
configurations:
- params.yaml


resources:
- ../crd
- ../rbac
- ../manager
- ../prometheus
- ../scc

images:
- name: kuberay/operator
  newName: quay.io/opendatahub/kuberay-operator
  newTag: v0.5.0
replacements:
- source:
    fieldPath: data.namespace
    kind: ConfigMap
    name: codeflare-stack-config
    version: v1
  targets:
  - fieldPaths:
    - subjects.0.namespace
    select:
      group: rbac.authorization.k8s.io
      kind: ClusterRoleBinding
      name: kuberay-operator
      version: v1
  - fieldPaths:
    - users.0
    options:
      delimiter: ':'
      index: 2
    select:
      group: security.openshift.io
      kind: SecurityContextConstraints
      name: run-as-ray-user
      version: v1
