apiVersion: v1
kind: Service
metadata:
  name: service
  labels:
    control-plane: controller-manager
    app.kubernetes.io/created-by: data-science-pipelines-operator
spec:
  ports:
    - name: metrics
      port: 8080
  selector:
    control-plane: controller-manager
