---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
namespace: opendatahub
commonLabels:
  app.kubernetes.io/part-of: odh-notebook-controller
  component.opendatahub.io/name: kf-notebook-controller
  opendatahub.io/component: "true"

configMapGenerator:
  - name: config
    behavior: merge
    literals:
      - USE_ISTIO=false
      - ADD_FSGROUP=false

patches:
  - path: remove_namespace_patch.yaml
  - path: manager_openshift_patch.yaml
  - path: manager_service_openshift_patch.yaml

configurations:
- params.yaml