apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- minimal-notebook-imagestream.yaml
- generic-data-science-notebook-imagestream.yaml
- minimal-gpu-notebook-imagestream.yaml
- pytorch-notebook-imagestream.yaml
- tensorflow-notebook-imagestream.yaml
- trustyai-notebook-imagestream.yaml
- ../../base

configMapGenerator:
- envs:
  - params.env
  name: notebooks-parameters
generatorOptions:
  disableNameSuffixHash: true

configurations:
- params.yaml

labels:
- includeSelectors: true
  pairs:
    component.opendatahub.io/name: jupyterhub
    opendatahub.io/component: "true"

replacements:
- source:
    fieldPath: data.odh-minimal-notebook-image-n
    kind: ConfigMap
    name: notebooks-parameters
    version: v1
  targets:
  - fieldPaths:
    - spec.tags.0.from.name
    select:
      group: image.openshift.io
      kind: ImageStream
      name: s2i-minimal-notebook
      version: v1
- source:
    fieldPath: data.odh-minimal-notebook-image-n-1
    kind: ConfigMap
    name: notebooks-parameters
    version: v1
  targets:
  - fieldPaths:
    - spec.tags.1.from.name
    select:
      group: image.openshift.io
      kind: ImageStream
      name: s2i-minimal-notebook
      version: v1
- source:
    fieldPath: data.odh-minimal-gpu-notebook-image-n
    kind: ConfigMap
    name: notebooks-parameters
    version: v1
  targets:
  - fieldPaths:
    - spec.tags.0.from.name
    select:
      group: image.openshift.io
      kind: ImageStream
      name: minimal-gpu
      version: v1
- source:
    fieldPath: data.odh-minimal-gpu-notebook-image-n-1
    kind: ConfigMap
    name: notebooks-parameters
    version: v1
  targets:
  - fieldPaths:
    - spec.tags.1.from.name
    select:
      group: image.openshift.io
      kind: ImageStream
      name: minimal-gpu
      version: v1
- source:
    fieldPath: data.odh-pytorch-gpu-notebook-image-n
    kind: ConfigMap
    name: notebooks-parameters
    version: v1
  targets:
  - fieldPaths:
    - spec.tags.0.from.name
    select:
      group: image.openshift.io
      kind: ImageStream
      name: pytorch
      version: v1
- source:
    fieldPath: data.odh-pytorch-gpu-notebook-image-n-1
    kind: ConfigMap
    name: notebooks-parameters
    version: v1
  targets:
  - fieldPaths:
    - spec.tags.1.from.name
    select:
      group: image.openshift.io
      kind: ImageStream
      name: pytorch
      version: v1
- source:
    fieldPath: data.odh-generic-data-science-notebook-image-n
    kind: ConfigMap
    name: notebooks-parameters
    version: v1
  targets:
  - fieldPaths:
    - spec.tags.0.from.name
    select:
      group: image.openshift.io
      kind: ImageStream
      name: s2i-generic-data-science-notebook
      version: v1
- source:
    fieldPath: data.odh-generic-data-science-notebook-image-n-1
    kind: ConfigMap
    name: notebooks-parameters
    version: v1
  targets:
  - fieldPaths:
    - spec.tags.1.from.name
    select:
      group: image.openshift.io
      kind: ImageStream
      name: s2i-generic-data-science-notebook
      version: v1
- source:
    fieldPath: data.odh-tensorflow-gpu-notebook-image-n
    kind: ConfigMap
    name: notebooks-parameters
    version: v1
  targets:
  - fieldPaths:
    - spec.tags.0.from.name
    select:
      group: image.openshift.io
      kind: ImageStream
      name: tensorflow
      version: v1
- source:
    fieldPath: data.odh-tensorflow-gpu-notebook-image-n-1
    kind: ConfigMap
    name: notebooks-parameters
    version: v1
  targets:
  - fieldPaths:
    - spec.tags.1.from.name
    select:
      group: image.openshift.io
      kind: ImageStream
      name: tensorflow
      version: v1
- source:
    fieldPath: data.odh-trustyai-notebook-image-n
    kind: ConfigMap
    name: notebooks-parameters
    version: v1
  targets:
  - fieldPaths:
    - spec.tags.0.from.name
    select:
      group: image.openshift.io
      kind: ImageStream
      name: odh-trustyai-notebook
      version: v1
