apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    opendatahub.io/notebook-image: "true"
  annotations:
    opendatahub.io/notebook-image-url: "https://github.com/red-hat-data-services/notebooks/tree/main/jupyter/minimal"
    opendatahub.io/notebook-image-name: "CUDA"
    opendatahub.io/notebook-image-desc: "Jupyter notebook image with GPU support and minimal dependency set to start experimenting with Jupyter environment."
    opendatahub.io/notebook-image-order: "30"
  name: minimal-gpu
spec:
  lookupPolicy:
    local: true
  tags:
  # N Version of the image (2023a-20230510-e348fda)
  - annotations:
        opendatahub.io/notebook-software: '[{"name":"CUDA","version":"11.8"},{"name":"Python","version":"v3.9"}]'
        opendatahub.io/notebook-python-dependencies: '[{"name":"JupyterLab","version":"3.5"},{"name":"Notebook","version":"6.5"}]'
        openshift.io/imported-from: quay.io/modh/cuda-notebooks
        opendatahub.io/workbench-image-recommended: 'true'
    from:
      kind: DockerImage
      name: quay.io/modh/cuda-notebooks@sha256:50e1ab299f12310b8187034648620ca8b03e0f82acc1abeb9e96df0af9ebc77c
    name: "2023.1"
    referencePolicy:
      type: Local
  # N-1 Version of the image
  - annotations:
        opendatahub.io/notebook-software: '[{"name":"CUDA","version":"11.4"},{"name":"Python","version":"v3.8"}]'
        opendatahub.io/notebook-python-dependencies: '[{"name":"JupyterLab","version":"3.2"},{"name":"Notebook","version":"6.4"}]'
        openshift.io/imported-from: quay.io/modh/cuda-notebooks
    from:
      kind: DockerImage
      name: quay.io/modh/cuda-notebooks@sha256:348fa993347f86d1e0913853fb726c584ae8b5181152f0430967d380d68d804f
    name: "1.2"
    referencePolicy:
      type: Local
