apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    opendatahub.io/notebook-image: "true"
    rhods/prebuilt: "true"
  annotations:
    opendatahub.io/notebook-image-url: "https://github.com/red-hat-data-services/s2i-minimal-notebook"
    opendatahub.io/notebook-image-name: "Minimal Python"
    opendatahub.io/notebook-image-desc: "Jupyter notebook image with minimal dependency set to start experimenting with Jupyter environment."
    opendatahub.io/notebook-image-order: "10"
  name: s2i-minimal-notebook
spec:
  lookupPolicy:
    local: true
  tags:
  - annotations:
      opendatahub.io/notebook-software: '[{"name":"Python","version":"v3.8"}]'
      opendatahub.io/notebook-python-dependencies: '[{"name":"JupyterLab","version": "3.2.4"}, {"name": "Notebook","version": "6.4"}]'
      openshift.io/imported-from: quay.io/modh/odh-minimal-notebook-container
      opendatahub.io/default-image: "true"
    from:
      kind: DockerImage
      name: quay.io/modh/odh-minimal-notebook-container:latest
    name: "py3.8"
    referencePolicy:
      type: Local
