apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: odh-applications
namePrefix: data-science-pipelines-operator-
resources:
- ../crd
- ../rbac
- ../manager
- ../prometheus
- ../configmaps

# Parameterize images via KfDef in ODH
configMapGenerator:
- envs:
  - params.env
  name: dspo-parameters
configurations:
- params.yaml

replacements:
- source:
    fieldPath: data.IMAGES_APISERVER
    kind: ConfigMap
    name: dspo-parameters
    version: v1
  targets:
  - fieldPaths:
    - spec.template.spec.containers.0.env.0.value
    select:
      group: apps
      kind: Deployment
      name: controller-manager
      namespace: datasciencepipelinesapplications-controller
      version: v1
- source:
    fieldPath: data.IMAGES_ARTIFACT
    kind: ConfigMap
    name: dspo-parameters
    version: v1
  targets:
  - fieldPaths:
    - spec.template.spec.containers.0.env.1.value
    select:
      group: apps
      kind: Deployment
      name: controller-manager
      namespace: datasciencepipelinesapplications-controller
      version: v1
- source:
    fieldPath: data.IMAGES_OAUTHPROXY
    kind: ConfigMap
    name: dspo-parameters
    version: v1
  targets:
  - fieldPaths:
    - spec.template.spec.containers.0.env.2.value
    select:
      group: apps
      kind: Deployment
      name: controller-manager
      namespace: datasciencepipelinesapplications-controller
      version: v1
- source:
    fieldPath: data.IMAGES_PERSISTENTAGENT
    kind: ConfigMap
    name: dspo-parameters
    version: v1
  targets:
  - fieldPaths:
    - spec.template.spec.containers.0.env.3.value
    select:
      group: apps
      kind: Deployment
      name: controller-manager
      namespace: datasciencepipelinesapplications-controller
      version: v1
- source:
    fieldPath: data.IMAGES_SCHEDULEDWORKFLOW
    kind: ConfigMap
    name: dspo-parameters
    version: v1
  targets:
  - fieldPaths:
    - spec.template.spec.containers.0.env.4.value
    select:
      group: apps
      kind: Deployment
      name: controller-manager
      namespace: datasciencepipelinesapplications-controller
      version: v1
- source:
    fieldPath: data.IMAGES_CACHE
    kind: ConfigMap
    name: dspo-parameters
    version: v1
  targets:
  - fieldPaths:
    - spec.template.spec.containers.0.env.5.value
    select:
      group: apps
      kind: Deployment
      name: controller-manager
      namespace: datasciencepipelinesapplications-controller
      version: v1
- source:
    fieldPath: data.IMAGES_MOVERESULTSIMAGE
    kind: ConfigMap
    name: dspo-parameters
    version: v1
  targets:
  - fieldPaths:
    - spec.template.spec.containers.0.env.6.value
    select:
      group: apps
      kind: Deployment
      name: controller-manager
      namespace: datasciencepipelinesapplications-controller
      version: v1
- source:
    fieldPath: data.IMAGES_MARIADB
    kind: ConfigMap
    name: dspo-parameters
    version: v1
  targets:
  - fieldPaths:
    - spec.template.spec.containers.0.env.7.value
    select:
      group: apps
      kind: Deployment
      name: controller-manager
      namespace: datasciencepipelinesapplications-controller
      version: v1
- source:
    fieldPath: data.IMAGES_DSPO
    kind: ConfigMap
    name: dspo-parameters
    version: v1
  targets:
  - fieldPaths:
    - spec.template.spec.containers.0.image
    select:
      group: apps
      kind: Deployment
      name: controller-manager
      namespace: datasciencepipelinesapplications-controller
      version: v1
