apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
- envs:
  - params.env
  name: codeflare-stack-config
configurations:
- params.yaml

resources:
- codeflare-notebook-imagestream.yaml
- instascale.yaml
- mcad.yaml
- ../rbac

replacements:
- source:
    fieldPath: data.namespace
    kind: ConfigMap
    name: codeflare-stack-config
    version: v1
  targets:
  - fieldPaths:
    - subjects.0.namespace
    select:
      group: rbac.authorization.k8s.io
      kind: ClusterRoleBinding
      name: mcad-controller-ray-clusterrolebinding
      version: v1
