varReference:
  - path: spec/template/spec/containers[]/image
    kind: Deployment
    apiVersion: apps/v1
  - path: data
    kind: ConfigMap
  - path: spec/template/spec/containers[]/env/value
    kind: Deployment
  - path: subjects[]/namespace
    kind: ClusterRoleBinding