apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: rhods-monitor-federation
  labels:
    monitor-component: rhods-resources
    team: rhods
spec:
  endpoints:
    - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      bearerTokenSecret:
        key: ""
      honorLabels: true
      params:
        'match[]':
          - '{__name__= "rhods_total_users"}'
          - '{__name__= "rhods_aggregate_availability"}'
      path: /federate
      port: https
      scheme: https
      tlsConfig:
        insecureSkipVerify: true
      scrapeTimeout: 10s
      interval: 30s
  namespaceSelector:
    matchNames:
      - redhat-ods-monitoring
  selector:
    matchLabels:
      app: prometheus
